package uasoop;


import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static uasoop.koneksi.getConnection;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Nanda Fredika
 * TI - MTI / L
 * 2201010107
 */
public class perpusform extends javax.swing.JFrame {
    DefaultTableModel tb = new DefaultTableModel();
    /**
     * Creates new form perpusform
     */
    public perpusform() throws SQLException {
        initComponents();
        tabel.setModel(tb);
        tb.addColumn("id");
        tb.addColumn("judul");
        tb.addColumn("ambil");
        tb.addColumn("kembali");
        list_all();
    }
    
    private void list_all() throws SQLException {
    Connection cnn = getConnection();
    if (cnn != null && !cnn.isClosed()) {
        tb.getDataVector().removeAllElements();
        tb.fireTableDataChanged();

        try {
            String sql = "SELECT * FROM databuku ORDER BY id;";
            PreparedStatement ps = cnn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Object[] dta = new Object[4];
                dta[0] = rs.getInt("id");
                dta[1] = rs.getString("judul");
                dta[2] = rs.getString("ambil");
                dta[3] = rs.getString("kembali");
                tb.addRow(dta);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
        } finally {
            cnn.close();
        }
    } else {
        JOptionPane.showMessageDialog(null, "Koneksi ke database gagal.");
    }
}

    
    private void storedata() throws SQLException{
        Connection cnn = getConnection();
        String BK = formbuku.getText();
        String AM = formambil.getText();
        String KM = formkembali.getText();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("INSERT INTO databuku (judul, ambil, kembali)VALUES(?,?,?);");
            ps.setString(1, BK);
            ps.setString(2, AM);
            ps.setString(3, KM);
            ps.executeUpdate();

        }  
    }
    
    private void UpdateData () throws SQLException{
    Connection cnn = getConnection();
    if(!cnn.isClosed()){
//        String ID = formnama.getText();
        String id = labelid.getText();
        String NM = formbuku.getText();
        String AL = formambil.getText();
        String TL = formkembali.getText();
        PreparedStatement ps = cnn.prepareStatement("UPDATE databuku SET judul=?, ambil=?, kembali=? WHERE id=?");    
        ps.setString(1, NM);
        ps.setString(2, AL);    
        ps.setString(3, TL);
        ps.setString(4, id);
        ps.executeUpdate();
        }
   }
    
    private void DestroyData() throws SQLException{
        Connection cnn = getConnection();
    if(!cnn.isClosed()){
//        String ID = formnama.getText();
        PreparedStatement ps = cnn.prepareStatement("DELETE FROM databuku WHERE id=?");    
        ps.setString(1, labelid.getText());
        ps.executeUpdate();
        cnn.close();
        }
    }
    
    private void loadfoto(String idteman){
        String pas0 = "img/foto0.png";
        String pas = "img/foto"+idteman+".png";
        
        
        BufferedImage bimg = loadIMG.loadImage(pas);
        if(bimg == null){
            bimg = loadIMG.loadImage(pas0);
        }
        ImageIcon icoimg = new ImageIcon(bimg);
        pasfoto.setIcon(icoimg);
        
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelid = new javax.swing.JLabel();
        formbuku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        formambil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        formkembali = new javax.swing.JTextField();
        btnbaru = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        pasfoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel1.setText("PERPUSTAKAAN");

        jLabel2.setText("ID :");

        labelid.setText("- ");

        formbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formbukuActionPerformed(evt);
            }
        });

        jLabel3.setText("Judul Buku :");

        formambil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formambilActionPerformed(evt);
            }
        });

        jLabel4.setText("Tanggal Pengambilan :");

        jLabel5.setText("Tanggal Pengembalian :");

        formkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formkembaliActionPerformed(evt);
            }
        });

        btnbaru.setText("Baru");
        btnbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbaruActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnbatal.setText("Tutup");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        pasfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/foto0.png"))); // NOI18N
        pasfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(pasfoto))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)))
                            .addComponent(formbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(formambil, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnubah)
                        .addGap(33, 33, 33)
                        .addComponent(btnbatal)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelid))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pasfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formambil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbatal)
                    .addComponent(btnubah)
                    .addComponent(btnhapus)
                    .addComponent(btnbaru))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formbukuActionPerformed

    private void btnbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbaruActionPerformed
        if(btnbaru.getText().equals("Tambah")){
        btnbaru.setText("Simpan");
        btnbatal.setText("Batal");
        btnhapus.setEnabled(false);
        
        labelid.setText("");
        formbuku.setText("");
        formambil.setText("");
        formkembali.setText("");
    }
    else{
        try {
            storedata();
            list_all();
        } catch (SQLException ex) {
            Logger.getLogger(perpusform.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnbaru.setText("Tambah");
        btnbatal.setText("Tutup");
        btnhapus.setEnabled(true);
    }

    }//GEN-LAST:event_btnbaruActionPerformed

    private void formkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formkembaliActionPerformed

    private void formambilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formambilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formambilActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try{
            DestroyData();
            list_all();
            
        }catch(SQLException ex){
            Logger.getLogger(perpusform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        if(btnbatal.getText().equals("Tutup")){
            int jtp = JOptionPane.showOptionDialog(this, "Yakin akan menutup form ini?", 
                    "Konfirmasi Tutup Form.", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.WARNING_MESSAGE, 
                    null, 
                    null, 
                    null);
            if(jtp == JOptionPane.YES_OPTION){
            dispose();
            }
        }else{
            try {
                storedata();
            } catch (SQLException ex) {
                Logger.getLogger(perpusform.class.getName()).log(Level.SEVERE, null, ex);
            }
            btnbatal.setText("Tutup");
            btnbaru.setText("Baru");
            btnhapus.setEnabled(true);
        }
    }//GEN-LAST:event_btnbatalActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        labelid.setText(tabel.getValueAt(tabel.getSelectedRow(), 0).toString());
        formbuku.setText(tabel.getValueAt(tabel.getSelectedRow(), 1).toString());
        formambil.setText(tabel.getValueAt(tabel.getSelectedRow(), 2).toString());
        formkembali.setText(tabel.getValueAt(tabel.getSelectedRow(), 3).toString());
        loadfoto(labelid.getText());
    }//GEN-LAST:event_tabelMouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        try{
            UpdateData();
            list_all();
        }catch(SQLException ex){
            Logger.getLogger(perpusform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnubahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpusform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpusform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpusform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpusform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpusform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbaru;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnubah;
    private javax.swing.JTextField formambil;
    private javax.swing.JTextField formbuku;
    private javax.swing.JTextField formkembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelid;
    private javax.swing.JLabel pasfoto;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

}
